services:
  db:
    image: postgres:16
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1024"
      - "-c"
      - "max_pred_locks_per_transaction=1024"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"