services:
  test-db:
    image: postgres:18
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1024"
      - "-c"
      - "max_pred_locks_per_transaction=1024"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
#    volumes:
#    - ~/projects/dump/local-db-volume:/var/lib/postgresql/data
